#Run apt-get to update the cache
- name: Update software
  become: yes
  apt:
    update_cache: yes
    cache_valid_time: 3600
    upgrade: yes

- name: Check if reboot is required
  stat: 
    path: /var/run/reboot-required
  register: reboot_file

- name: Reboot required?
  when: reboot_file.stat.exists
  command: /bin/true
  notify: "server reboot"

- name: Ensure the 'pi' user is absent
  become: yes
  user:
    name: pi
    state: absent
    remove: yes

- name: Ensure the hostname is set correctly
  become: yes
  hostname:
    name: "{{ inventory_hostname }}"

- name: Ensure Timezone to {{ timezone }}
  become: yes
  timezone:
    name: "{{ timezone }}"

- name: Ensure UFW installed and present
  become: yes
  apt:
    name: ufw
    state: present

- name: Configure ufw to be enabled and allow SSH
  become: yes
  ufw:
    state: enabled
    rule: allow
    name: OpenSSH

- name: Disable SSH Password logins
  become: yes
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^#?PasswordAuthentication'
    line: 'PasswordAuthentication no'
  notify: restart ssh