# Invocation
# ansible-playbook -i hosts ./03-ipservices.yml

- name: Configure File Server
  hosts: ipservices
  remote_user: "{{ admin_user }}"
  gather_facts: false
  become: yes

  tasks:
    # Import the server base role
    - import_role:
        name: server_base

    #DHCP server must have static IP
    - name: Set static IP address
      blockinfile:
        path: /etc/dhcpcd.conf
        block: |
          interface {{ interface }}
            static ip_address={{ ip_addr }}/24
            static routers={{ router }}
            static domain_name_servers={{ router }}
            static domain_search={{ domain }}
      notify: "server reboot"

    - name: Update Hosts file contents with static servers
      blockinfile:
        path: /etc/hosts
        block: "{{ static_hosts | join('\n') }}"
      notify: restart-dnsmasq

    - name: Install dnsmasq
      apt:
        name: dnsmasq
        state: present

    - name: Configure dnsmasq
      template:
        src: templates/dnsmasq.conf
        dest: /etc/dnsmasq.conf
        owner: root
        group: root
        mode: "u=rw,g=r,o=r"
      notify: restart-dnsmasq

    - name: Open firewall ports
      ufw:
        rule: allow
        port: "{{ item }}"
      with_items:
        - 53
        - 67

  handlers:  
    - name: restart-dnsmasq
      become: yes
      service:
        name: dnsmasq
        state: restarted
