# Invocation
# ansible-playbook -i hosts ./01-pi-fileserver.yml


- name: Configure Basic server settings
  hosts: pi
  remote_user: "{{ admin_user }}"
  gather_facts: false

  roles:
    # - update_software
    # - basic_config
    - install_netatalk

