# Invocation
# ansible-playbook -i hosts ./02-fileserver.yml

- name: Configure File Server
  hosts: fileservers
  remote_user: "{{ admin_user }}"
  gather_facts: false

  tasks:
    - name: add to fstab
      become: yes
      mount: 
        fstype: "{{ item.type }}"
        src: "UUID={{ item.uuid }}"
        path: "{{ item.mount }}"
        state: mounted
        opts: "defaults,relatime"
      loop: "{{ filesystems }}"

    - name: Create fileserver user
      become: yes
      user:
        name: "{{ fileshare_user }}"
        generate_ssh_key: yes
        password: "{{ admin_password }}"
        shell: /bin/bash

    - name: Add management ssh keys to fileshare user
      become: yes
      authorized_key:
        user: "{{ fileshare_user }}"
        state: present
        key: "{{ admin_ssh_key }}"

    - import_role:
        name: fileserver 
