# Invocation
# ansible-playbook -i hosts ./02-fileserver.yml

- name: Configure File Server
  hosts: fileservers
  remote_user: "{{ admin_user }}"
  gather_facts: false

  tasks:
  - import_role:
      name: mount_disks

  - name: Create fileserver user
    become: yes
    user:
      name: "{{ fileshare_user }}"
      generate_ssh_key: yes
      ssh_key_bits: 2048
      ssh_key_file: .ssh/id_rsa
      password: "{{ admin_password }}"
      shell: /bin/bash

  - name: Add management ssh keys to fileshare user authorized keys
    become: yes
    authorized_key:
      user: "{{ fileshare_user }}"
      state: present
      key: "{{ admin_ssh_key }}"

  - import_role:
      name: install_netatalk 

  - import_role:
      name: install_resiliosync