# Invocation
# ansible-playbook -i hosts ./01-harden-pi.yml

#In this playbook we'll apply some basic hardening.
# 1. Delete the default pi user
# 2 . Install ufw, allow ssh and enable
# 3 . Disable password ssh logins

- name: Pi basic hardening
  hosts: pi
  remote_user: "{{ admin_user }}"
  gather_facts: false
  become: yes

  tasks:
    - name: Remove the default 'pi' user
      user:
        name: pi
        state: absent
        remove: yes

    - name: Install ufw
      apt:
        name: ufw
        state: present

    - name: Configure ufw to be enabled and allow SSH
      ufw:
        state: enabled
        rule: allow
        name: OpenSSH

    - name: Disable SSH Password logins
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^#?PasswordAuthentication'
        line: 'PasswordAuthentication no'
      notify: restart ssh

  handlers:
    - name: restart ssh
      service:
        name: ssh
        state: restarted


