# DANGER WILL ROBINSON!
# When run this playbook will trigger the deletion of all partitions
# and the creation of a new XFS filesystem on the listed disks
# THIS WILL DELETE ANYTHING ON THE DEVICES LISTED IN {{ gluster_data_disks }}

- name: Format data disks
  hosts: Cluster
  become: yes
  gather_facts: false

  tasks:
    - name: Install XFS tools
      apt:
        name: 
          - xfsprogs
        state: present
    
    - name: Get Gluster physical device partition table
      parted: 
        device: "{{ item.device }}"
        unit: MiB
      register: device_info
      loop: "{{ gluster_data_disks }}"

    - name: Delete every partition.
      parted:
        device: "{{ item.0.disk.dev }}"
        number: "{{ item.1.num }}"
        state: absent
      loop: "{{ device_info.results | subelements('partitions') }}"

    - name: Make partition
      parted:
        device: "{{ item.device }}"
        label: gpt
        name: "{{ item.label }}"
        number: 1
        state: present
        part_start: 0%
        part_end: 100%
      loop: "{{ gluster_data_disks }}"

    - name: Create the xfs filesystem on each data device
      filesystem:
        fstype: xfs
        dev: "{{ item.device }}1"
        force: true
      loop: "{{ gluster_data_disks }}"
