# This playbook does the day-to-day maintenance on the cluster of pis

- name: Rasbian Maintenance tasks
  hosts: Raspbian
  become: yes
  serial: 1
  gather_facts: false
  tags: core
  roles:
    - raspbian-server-core

- name: Install DHCP Servers
  hosts: DHCPServers
  become: yes
  gather_facts: false
  tags: DHCP
  roles:
    - dnsmasq

- name: Install cluster services
  hosts: Cluster
  become: yes
  gather_facts: true
  tags: cluster-services
  roles:
    - role: gluster
      tags: gluster
    - role: docker
      tags: docker
    - role: telegraf
      tags: telegraf

- name: Deploy swarm services as non-root user
  hosts: Cluster
  gather_facts: false
  tags: swarm-services
  roles:
    - swarm-services
