# This playbook does the day-to-day maintenance on the cluster of pis

- name: Rasbian Maintenance tasks
  hosts: Raspbian
  become: yes
  serial: 1
  gather_facts: false
  roles:
    - role: raspbian-core
      tags: raspbian-core

- name: Install DHCP Servers
  hosts: DHCPServers
  become: yes
  gather_facts: false
  roles:
    - role: dnsmasq
      tags: dnsmasq

- name: Install Ubiquiti Controller
  hosts: UniFiControllers
  become: yes
  gather_facts: false
  roles:
    - role: ubiquiti-controller
      tags: ubiquiti-controller

- name: Install Services on each cluster node
  hosts: Cluster
  become: yes
  gather_facts: true
  tags: cluster-services
  roles:
    - role: gluster
      tags: gluster
    - role: docker
      tags: docker
    - role: telegraf
      tags: telegraf
    - role: docker-swarm
      tags: docker-swarm
