# This playbook does the day-to-day maintenance on the cluster of pis

- name: Rasbian Maintenance tasks
  hosts: Raspbian
  become: yes
  serial: 1
  gather_facts: false
  roles:
    - role: raspbian-server-core
      tags: core

- name: Install DHCP Servers
  hosts: DHCPServers
  become: yes
  gather_facts: false
  roles:
    - role: dnsmasq
      tags: dnsmasq

- name: Install cluster services
  hosts: Cluster
  become: yes
  gather_facts: true
  tags: cluster-services
  roles:
    - role: gluster
      tags: gluster
    - role: docker
      tags: docker
    - role: telegraf
      tags: telegraf

- name: Deploy swarm services as non-root user
  hosts: Cluster
  gather_facts: false
  roles:
    - role: docker-netatalk
      tags: docker-netatalk
    - role: docker-vizualizer
      tags: docker-vizualizer
