# This playbook does the day-to-day maintenance on the cluster of pis

- name: Rasbian Maintenance tasks
  hosts: Raspbian
  become: yes
  serial: 1
  gather_facts: false
  roles:
    - role: raspbian-core
      tags: raspbian-core

- name: Install LAN services
  hosts: DnsServers
  become: yes
  gather_facts: false
  tags: lan-services
  roles:
    - role: dnsmasq
      tags: dnsmasq
    - role: ubiquiti-controller
      tags: ubiquiti-controller


- name: Install Services on each cluster node
  hosts: Cluster
  become: yes
  gather_facts: false
  tags: cluster-services
  roles:
    - role: gluster
      tags: gluster
    - role: docker
      tags: docker
    - role: rsyncserver
      tags: rsyncserver

- name: Install Cluster Services
  hosts: ClusterLeader
  become: yes
  gather_facts: false
  roles:
    - role: docker-swarm
      tags: docker-swarm
