# This playbook deploys all the services
- name: Install LAN services
  hosts: LanServers
  become: yes
  gather_facts: false
  tags: lan-services
  roles:
    - role: dnsmasq
      tags: dnsmasq
    - role: ubiquiti-controller
      tags: ubiquiti-controller

- name: Install services on the cluster
  hosts: Cluster
  become: yes
  gather_facts: false
  tags: cluster-services
  roles:
    - role: gluster
      tags: gluster
    - role: docker
      tags: docker


