# This playbook does the day-to-day maintenance on the cluster of pis

# Update the software serially, prevents every box from rebooting at once.
- name: Update Software
  hosts: Raspbian
  become: yes
  serial: 1
  gather_facts: false
  roles:
    - role: update-software
      tags: update-software

- name: Rasbian Universal tasks
  hosts: Raspbian
  become: yes
  gather_facts: false
  roles:
    - role: raspbian-core
      tags: raspbian-core

- name: Install LAN services
  hosts: LanServers
  become: yes
  gather_facts: false
  tags: lan-services
  roles:
    - role: dnsmasq
      tags: dnsmasq
    - role: ubiquiti-controller
      tags: ubiquiti-controller
    - role: ddclient
      tags: ddclient

- name: Install services on the cluster
  hosts: Cluster
  become: yes
  gather_facts: false
  tags: cluster-services
  roles:
    - role: gluster
      tags: gluster
    - role: docker
      tags: docker


