# Roles that apply to all Rasbian boxes
- name: Update Software
  hosts: Raspbian
  become: yes
  serial: 1
  gather_facts: false
  roles:
    - role: update-software
      tags: update-software
    - role: raspbian-core
      tags: raspbian-core
    - role: telegraf
      tags: telegraf