# Run this task async as it can take some time, especially on a first boot
- name: Update software
  apt:
    update_cache: yes
    cache_valid_time: 3600
    upgrade: 'yes'
    autoremove: yes
  async: 600
  poll: 20

- name: Check if reboot is required
  stat: 
    path: /var/run/reboot-required
  register: reboot_file

- name: Reboot required?
  when: reboot_file.stat.exists
  command: /bin/true
  notify: RebootServer