#List of external disks.
data_disks: 
  - /dev/sda

#Gluster brick to mount
gluster_partitions:
  /dev/sda1: /data/gluster/SharedMedia/brick0

#Volumes to mount
gluster_volumes: 
  SharedMedia: /data/gluster/SharedMedia/brick0/brick

docker_user: dockeradmin

#Set all the pis to be headless
pi_headless: true
