#List of external disks.
data_disks: 
  - device: /dev/sda
    label: ClusterShared

gluster_storage:
  - name: ClusterShared
    src: PARTLABEL=ClusterShared
    path: /data/gluster/ClusterShared/brick0
    nodes: "{{ groups.Cluster }}"

#Set all the pis to be headless
pi_headless: true

# Define variables for the docker swarm
docker_volume_root: /mnt/gluster/ClusterShared/DockerVolumes
docker_swarm:
  gluster: true
  netatalk:
    user:
      name: netshare
      id: 200
      password: "{{ vault_netatalk_passwd }}"
    image: njdcourtney/docker-netatalk:latest
    volumes:
      - "{{ docker_volume_root }}/netshare"
  vizualizer:
    image: njdcourtney/visualizer-custom:latest
  influxdb:
    image: influxdb
    volume: "{{ docker_volume_root }}/influxdb"
  chronograf:
    image: chronograf
    volume: "{{ docker_volume_root }}/chronograf"


