#List of external disks.
data_disks: 
  - device: /dev/sda
    label: ClusterShared

#Gluster brick to mount
gluster_partitions:
  - src: LABEL=ClusterShared
    path: /data/gluster/ClusterShared/brick0

#Volumes to mount
gluster_volumes: 
  - name: ClusterShared
    bricks: /data/gluster/ClusterShared/brick0/brick

#Set all the pis to be headless
pi_headless: true

# Variables for various Docker services
netatalk:
  user: netshare
  uid: 200
  gid: 200
  passwd: "{{ vault_netatalk_passwd }}"
  image: njdcourtney/docker-netatalk:2019-05-07a
  directory: /mnt/gluster/SharedMedia/netshare
  force: false
