#List of external disks.
data_disks: 
  - device: /dev/sda
    label: ClusterShared

gluster_storage:
  - name: ClusterShared
    src: PARTLABEL=ClusterShared
    path: /data/gluster/ClusterShared/brick0
    nodes: "{{ groups.Cluster }}"

#Set all the pis to be headless
pi_headless: true

# Define any additional users that the docker containers need
docker_users:
  netshare:
    id: 200
    password: "{{ vault_netatalk_passwd }}"

# Define any directories that will be needed for Docker Volumes
docker_volume_root: /mnt/gluster/ClusterShared/DockerVolumes
docker_volumes:
  netatalk: "{{ docker_volume_root }}/netshare"
  influxdb: "{{ docker_volume_root }}/influxdb"
  chronograf: "{{ docker_volume_root }}/chronograf"

#List any images to pre-pull to all nodes to speed up replication
docker_images:
  netatalk: njdcourtney/docker-netatalk:latest
  vizualizer: njdcourtney/visualizer-custom:latest
  influxdb: influxdb
  chronograf: chronograf
