#List of external disks.
data_disks: 
  - device: /dev/sda
    label: ClusterShared

#Gluster brick to mount
gluster_partitions:
  - src: PARTLABEL=ClusterShared
    path: /data/gluster/ClusterShared/brick0

#Volumes to mount
gluster_volumes: 
  - name: ClusterShared
    bricks: /data/gluster/ClusterShared/brick0/brick

#Set all the pis to be headless
pi_headless: true

# Define any additional users that the docker containers need
docker_users:
  - name: netshare
    uid: 200
    gid: 200
    password: "{{ vault_netatalk_passwd }}"

# Define any directories that will be needed for Docker Volumes
docker_volume_root: /mnt/gluster/ClusterShared/DockerVolumes
docker_volumes:
  netatalk: "{{ docker_volume_root }}/netshare"
  influxdb: "{{ docker_volume_root }}/influxdb"
  chronograf: "{{ docker_volume_root }}/chronograf"

#List any images to pre-pull to all nodes to speed up replication
docker_images:
  netatalk: njdcourtney/docker-netatalk:2019-05-07a
  vizualizer: njdcourtney/visualizer-custom:latest
  influxdb: influxdb
  chronograf: chronograf

#Define the stacks to deploy
docker_stacks:
  tickstack:
      version: "3.7"
      services:
        influxdb:
          image: "{{ docker_images.influxdb }}"
          ports: 
            - "8086:8086"
          volumes:
            - type: bind
              source: "{{ docker_volumes.influxdb}}"
              target: /var/lib/influxdb
          networks:
            - tickstacknet
        chronograf:
          image: "{{ docker_images.chronograf }}"
          ports: 
            - "8888:8888"
          volumes:
            - type: bind
              source: "{{ docker_volumes.chronograf }}"
              target: /var/lib/chronograf
          networks:
            - tickstacknet
      networks:
        tickstacknet: