gluster_storage:
  - name: ClusterShared
    src: PARTLABEL=ClusterShared
    path: /data/gluster/ClusterShared/brick0
    nodes: "{{ groups.Cluster }}"
  - name: ClusterBulk
    src: PARTLABEL=ClusterBulk
    path: /data/gluster/ClusterBulk/brick0
    nodes: "{{ groups.BulkStorage }}"

#Set all the pis to be headless
pi_headless: true

# Define variables for the docker swarm
docker_volume_root: /mnt/gluster/ClusterShared/DockerVolumes
docker_bulk_root: /mnt/gluster/ClusterBulk
docker_swarm:
  gluster: true
  netatalk:
    user:
      name: netshare
      id: 200
      password: "{{ vault_netatalk_passwd }}"
    image: njdcourtney/docker-netatalk:latest
    volumes:
      shared: "{{ docker_bulk_root }}/netshare/Shared"
      timemachine: "{{ docker_bulk_root }}/netshare/TimeMachine"
      config: "{{ docker_volume_root }}/netshare/config"
  vizualizer:
    image: njdcourtney/visualizer-custom:latest
  influxdb:
    image: influxdb
    volume: "{{ docker_volume_root }}/influxdb"
  chronograf:
    image: chronograf
    volume: "{{ docker_volume_root }}/chronograf"
  kapacitor:
    image: kapacitor
    volume: "{{ docker_volume_root }}/kapacitor"


