#List of external disks.
data_disks: 
  - device: /dev/sda
    label: ClusterShared

#Gluster brick to mount
gluster_partitions:
  - src: PARTLABEL=ClusterShared
    path: /data/gluster/ClusterShared/brick0

#Volumes to mount
gluster_volumes: 
  - name: ClusterShared
    bricks: /data/gluster/ClusterShared/brick0/brick

#Set all the pis to be headless
pi_headless: true

docker_volumes: /mnt/gluster/ClusterShared/DockerVolumes

# Variables for various Docker services
netatalk:
  user: netshare
  uid: 200
  gid: 200
  passwd: "{{ vault_netatalk_passwd }}"
  image: njdcourtney/docker-netatalk:2019-05-07a
  directory: "{{ docker_volumes}}/netshare"
  force: false

vizualizer:
  image: njdcourtney/visualizer-custom:latest

tickstack:
    version: "3.7"
    services:
      influxdb:
        image: influxdb
        ports: 
          - "8086:8086"
        volumes:
          - type: bind
            source: "{{ docker_volumes}}/influxdb"
            target: /var/lib/influxdb
        networks:
          - tickstacknet
      chronograf:
        image: chronograf
        ports: 
          - "8888:8888"
        volumes:
          - type: bind
            source: "{{ docker_volumes}}/chronograf"
            target: /var/lib/chronograf
        networks:
          - tickstacknet
    networks:
      tickstacknet: