- name: Mount Volume directories
  mount: 
    fstype: xfs
    src: "{{ partition }}"
    path: "/data/gluster/{{volume.key}}/brick{{index}}"
    state: mounted
    opts: "rw,inode64,noatime,nouuid"
  loop: "{{ volume.value | flatten(levels=1) }}"
  loop_control:
    loop_var: partition
    index_var: index

# Compute the brick names
- name: Process list of bricks into comma seperated string.
  set_fact:
    bricks: "{{ range(0, ( volume.value | length ) ) | map('regex_replace', '(.*)', '/data/gluster/{{volume.key}}/brick\\1/brick') | join(',') }}"

# Create the cluster volume
- name: Create Gluster Volume
  gluster_volume:
    state: present
    name: "{{ volume.key }}"
    bricks: "{{ bricks }}"
    cluster: "{{ groups.cluster }}"
    replicas: 2
  run_once: true

# The simple way to mount disks is to use the mount module and update fstab.
# This leads to a race condition where mount tries to mount the glusterfs
# before gluster is up, so we use Systemd to do it instead.

- name: Create the mount point
  file:
     path: "/mnt/gluster/{{volume.key}}"
     state: directory

- name: Add Systemd mount file
  template:
    src: gluster_mount.j2
    dest: "/etc/systemd/system/mnt-gluster-{{ volume.key }}.mount"

- name: Start systemd service
  systemd:
    daemon_reload: yes
    name: "mnt-gluster-{{ volume.key }}.mount"
    state: started