- name: Install glusterfs-server
  apt:
    name: 
      - glusterfs-server
    state: present

- name: Get facts
  gather_facts:

- name: Allow unrestricted communication between cluster peers
  ufw:
    rule: allow
    from_ip: "{{ hostvars[item].ansible_default_ipv4.address }}"
    comment: "Cluster peer"
  loop: "{{ groups.Cluster }}"

- name: Initialise Gluster pool on one node
  gluster_peer:
    state: present
    nodes: "{{ groups.Cluster }}"
  run_once: true

- name: Ensure all nodes are joined to the trusted pool
  gluster_peer:
    state: present
    nodes: "{{ groups.Cluster }}"

- name: Mount Data directories
  when: inventory_hostname in item.value
  mount: 
    fstype: xfs
    src: "PARTLABEL={{ item.key }}"
    path: "/data/gluster/{{ item.key }}/brick0"
    state: mounted
    opts: "rw,inode64,noatime,nouuid"
  loop: "{{ gluster_storage | dict2items }}"
  
- name: Create Gluster Volume
  gluster_volume:
    state: present
    name: "{{ item.key }}"
    bricks: "/data/gluster/{{ item.key }}/brick0/brick"
    cluster: "{{ item.value }}"
    replicas: 2
  loop: "{{ gluster_storage | dict2items }}"
  run_once: true

# The simple way to mount disks is to use the mount module and update fstab.
# This leads to a race condition where mount tries to mount the glusterfs
# before gluster is up, so we use Systemd to do it instead.

- name: Create the mount point
  file:
     path: "/mnt/gluster/{{item.key}}"
     state: directory
  loop: "{{ gluster_storage | dict2items }}"

- name: Add Systemd mount file
  template:
    src: gluster_mount.j2
    dest: "/etc/systemd/system/mnt-gluster-{{ item.key }}.mount"
  loop: "{{ gluster_storage | dict2items }}"

- name: Start systemd service
  systemd:
    daemon_reload: yes
    name: "mnt-gluster-{{ item.key }}.mount"
    state: started
    enabled: yes
  loop: "{{ gluster_storage | dict2items }}"
