- name: Install glusterfs-server
  apt:
    name: 
      - glusterfs-server
    state: present

- name: Start Gluster Service
  service:
    name: glusterd
    state: started
    enabled: yes

- name: Initialise Gluster pool on one node
  gluster_peer:
    state: present
    nodes: "{{ groups.Cluster }}"
  run_once: true

- name: Ensure all nodes are joined to the trusted pool
  gluster_peer:
    state: present
    nodes: "{{ groups.Cluster }}"

- name: Mount Data directories
  mount: 
    fstype: xfs
    src: "PARTLABEL={{ gluster_volume.label }}"
    path: "/data/gluster/{{ gluster_volume.label }}/brick0"
    state: mounted
    opts: "rw,inode64,noatime,nouuid"
  
- name: Create Gluster Volume
  gluster_volume:
    state:  present
    name: "{{ gluster_volume.label }}"
    bricks: "/data/gluster/{{ gluster_volume.label }}/brick0/brick"
    cluster: "{{ groups.Cluster }}"
    replicas: "{{ gluster_volume.replicas }}"
  run_once: true

# # The simple way to mount disks is to use the mount module and update fstab.
# # This leads to a race condition where mount tries to mount the gluster filesystem
# # before the glusterfs service is up, so we use Systemd to do it instead.

- name: Create the mount point
  file:
     path: "/mnt/gluster/{{ gluster_volume.label }}"
     state: directory

- name: Add Systemd mount file
  template:
    src: gluster_mount.j2
    dest: "/etc/systemd/system/mnt-gluster-{{ gluster_volume.label }}.mount"

- name: Start systemd service
  systemd:
    daemon_reload: yes
    name: "mnt-gluster-{{ gluster_volume.label }}.mount"
    state: started
    enabled: yes
