- name: Install Docker prerequisites
  apt:
    name: 
        - apt-transport-https
        - ca-certificates
        - python3-pip
        - git
    state: present

- name: Install Docker python modules (Ansible docker modules pre-reqs)
  pip:
    name: 
        - docker
        - jsondiff
        - pyyaml

- name: Add Docker Public Key
  apt_key:
    url: https://download.docker.com/linux/raspbian/gpg
    state: present

- name: Add Docker Repo
  apt_repository:
    repo: deb [arch=armhf] https://download.docker.com/linux/raspbian buster stable
    state: present
    update_cache: yes

- name: Install docker-ce
  apt:
    name: docker-ce
    install_recommends: no
    state: present

- name: Ensure the Docker service is started
  service:
    name: docker
    state: started
    enabled: yes
  
- name: Add admin user to docker group
  user:
    name: "{{ admin_user }}"
    groups: docker
    append: yes

- name: Update the systemd to run after the gluster mount is ready
  lineinfile:
    path: /etc/systemd/system/multi-user.target.wants/docker.service
    regexp: '^After='
    line: 'After=network-online.target firewalld.service containerd.service mnt-gluster-ClusterStorage.mount'
  
- name: Start the swarm with default parameters
  docker_swarm:
    state: present
  run_once: true
  delegate_to: "{{ groups.ClusterLeader[0] }}"
  register: swarm_info
      
- name: Add nodes to the swarm
  docker_swarm:
    state: join
    advertise_addr: "eth0"
    join_token: "{{ swarm_info.swarm_facts.JoinTokens.Manager }}"
    remote_addrs: [ "{{ hostvars[ groups.ClusterLeader[0] ].ansible_default_ipv4.address }}:2377" ]

- name: Deploy Cluster Services
  block:
    - import_tasks: docker-visualizer.yml
      tags: docker-visualizer
    - import_tasks: docker-monitoring.yml
      tags: docker-monitoring
    - import_tasks: docker-webservices.yml
      tags: docker-webservices
  tags: docker-services
  run_once: true
  delegate_to: "{{ groups.ClusterLeader[0] }}"

- name: Docker Cleanup
  docker_prune:
    containers: yes
    images: yes
  tags: docker-cleanup
