- name: Ensure the 'pi' user is absent
  user:
    name: pi
    state: absent
    remove: yes

- name: Ensure the hostname is set correctly
  hostname:
    name: "{{ inventory_hostname }}"

- name: Ensure Timezone to {{ timezone }}
  timezone:
    name: "{{ timezone }}"

- name: Ensure UFW installed and present
  apt:
    name: ufw
    state: present

- name: Configure ufw to be enabled and allow SSH
  ufw:
    state: enabled
    rule: allow
    name: OpenSSH

- name: Disable SSH Password logins
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^#?PasswordAuthentication'
    line: 'PasswordAuthentication no'
  notify: restart ssh

- name: Set static IP address
  when: static_ip is defined
  blockinfile:
    path: /etc/dhcpcd.conf
    block: |
        interface {{ static_ip.interface }}
        static ip_address={{ static_ip.addr }}/24
        static routers={{ static_ip.router }}
        static domain_name_servers={{ static_ip.name_servers }}
        static domain_search={{ static_ip.domain }}
  notify: "reboot-server"

- name: Import Headless server tasks
  import_tasks: headless.yml 