- name: Install ddclient
  package:
    name: ddclient
    state: present

- name: Configure ddclient
  template:
    src: ddclient.conf.j2
    dest: /etc/ddclient.conf
    owner: root
    group: root
    mode: '600'
  notify: restart-ddclient

