# Reboot the server 
- name: Sending Reboot commmand
  shell: sleep 2 && shutdown -r now 'Reboot required'
  async: 1
  poll: 0
  listen: RebootServer
  tags:
    - always

# Ensure that SSH has gone down before we wait for it to come back up again.
# Avoids race condition if shutting down is delayed for any reason.
- name: Check server has shutdown
  local_action: 
    module: wait_for
      host="{{ inventory_hostname }}"
      port=22
      state=stopped
      timeout=300
  become: no
  listen: RebootServer
  tags:
    - always


# Wait for SSH to come back up as sign that server has successfully rebooted
- name: Wait for SSH to be available
  local_action: 
    module: wait_for
      host="{{ inventory_hostname }}"
      port=22
      state=started
      delay=20
      timeout=300
  become: no
  listen: RebootServer
  tags:
    - always

