- name: Install XFS tools
  apt:
    name: 
      - xfsprogs
    state: present

- name: Set up disks
  include_tasks: initialise_disk.yml
  loop: "{{ gluster_devices }}"
  loop_control:
    loop_var: device