- name: Pre-pull netatalk image
  docker_image:
    source: pull
    name: "{{ docker_swarm.netatalk.image }}"

- name: Create Volume Directories
  file:
    name: "{{ item }}"
    state: directory
  loop: "{{ docker_swarm.netatalk.volumes }}"
  run_once: true

- name: Add netatalk group accounts
  group:
    name: "{{ docker_swarm.netatalk.user.name }}"
    gid: "{{ docker_swarm.netatalk.user.id }}"

- name: Create netatalk user accounts
  user:
    name: "{{ docker_swarm.netatalk.user.name }}"
    uid: "{{ docker_swarm.netatalk.user.id }}"
    group: "{{ docker_swarm.netatalk.user.name }}"

- name: Create secret with the filesystem user
  when: "'ClusterManagers' in group_names" 
  docker_secret:
    name: netatalk-user
    data: "{{ docker_swarm.netatalk.user.name }}:{{ docker_swarm.netatalk.user.password }}"
    state: present
  register: netatalk_secret
  run_once: true

# Create the networks
- name: Get info on netatalk-config network
  docker_network_info:
    name: netatalk-config
  register: netatalkConfigInfo

# docker_network module doesn't supprt --config-only (2.8) so create manually
- name: Create netatalk-config network
  when: not netatalkConfigInfo.exists
  command: "docker network create -d macvlan --config-only --subnet=192.168.0.0/24 --ip-range=192.168.0.192/32 --gateway=192.168.0.1 -o parent=eth0 netatalk-config" 

- name: Get info on netatalk-swarm network
  when: "'ClusterManagers' in group_names" 
  docker_network_info:
    name: netatalk-swarm
  register: netatalkSwarmInfo
  run_once: true

# docker_network module doesn't supprt --config-from (2.8) so create manually
- name: Create netatalk-swarm network
  when: 
    - "'ClusterManagers' in group_names" 
    - not netatalkSwarmInfo.exists
  command: "docker network create -d macvlan --scope swarm --config-from netatalk-config netatalk-swarm"
  run_once: true

- name: Deploy netatalk service
  when: "'ClusterManagers' in group_names" 
  docker_swarm_service:
    name: netatalk
    image: "{{ docker_swarm.netatalk.image }}"
    hostname: swarm-netatalk
    env:
      - "AFP_USER={{ docker_swarm.netatalk.user.name }}"
      - "AFP_UID={{ docker_swarm.netatalk.user.id }}"
      - "AFP_GID={{ docker_swarm.netatalk.user.id }}"
    publish: 
        - published_port: 548
          target_port: 548
        - published_port: 5353
          target_port: 5353
    mounts:
      - source: "{{ docker_swarm.netatalk.volumes[0] }}"
        target: /media/share
        type: bind
    networks:
      - netatalk-swarm
    secrets:
      - secret_id: "{{ netatalk_secret.secret_id}}"
        secret_name: netatalk-user
        filename: netatalk_passwd
    restart_config:
      condition: any
  run_once: true
