- name: Pre-pull Tickstack images
  docker_image:
    source: pull
    name: "{{ item }}"
  loop: 
    - "{{ docker_swarm.influxdb.image  }}"
    - "{{ docker_swarm.chronograf.image }}"
    - "{{ docker_swarm.kapacitor.image }}"

- name: Create Tickstack volume Directories
  file:
    name: "{{ item }}"
    state: directory
  loop:
    - "{{ docker_swarm.influxdb.volume  }}"
    - "{{ docker_swarm.chronograf.volume }}"
    - "{{ docker_swarm.kapacitor.volume }}"
  run_once: true

- name: Deploy the monitoring service stack
  when: "'ClusterManagers' in group_names" 
  docker_stack:
        state: present
        name: tickstack
        compose:
          - version: "3.7"
            services:
              influxdb:
                image: "{{ docker_swarm.influxdb.image }}"
                ports: 
                  - "8086:8086"
                volumes:
                  - type: bind
                    source: "{{ docker_swarm.influxdb.volume }}"
                    target: /var/lib/influxdb
                networks:
                  - tickstacknet
              chronograf:
                image: "{{ docker_swarm.chronograf.image }}"
                ports: 
                  - "8888:8888"
                volumes:
                  - type: bind
                    source: "{{ docker_swarm.chronograf.volume }}"
                    target: /var/lib/chronograf
                networks:
                    - tickstacknet
              kapacitor:
                image: "{{ docker_swarm.kapacitor.image }}"
                ports:
                  - "9092:9092"
                volumes:
                  - type: bind
                    source: "{{ docker_swarm.kapacitor.volume }}"
                    target: /var/lib/kapacitor
                environment:
                  KAPACITOR_INFLUXDB_0_URLS_0: http://influxdb:8086
                networks:
                    - tickstacknet
            networks:
                tickstacknet:
  run_once: true
