- name: Create Tickstack volume Directories
  file:
    name: "{{ item }}"
    state: directory
  loop:
    - "{{ docker_influxdb.volume  }}"
    - "{{ docker_chronograf.volume }}"
    - "{{ docker_kapacitor.volume }}"
  run_once: true

- name: Deploy the monitoring service stack
  docker_stack:
        state: present
        name: tickstack
        compose:
          - version: "3.7"
            services:
              influxdb:
                image: "{{ docker_influxdb.image }}"
                ports: 
                  - "8086:8086"
                volumes:
                  - type: bind
                    source: "{{ docker_influxdb.volume }}"
                    target: /var/lib/influxdb
                networks:
                  - tickstacknet
              chronograf:
                image: "{{ docker_chronograf.image }}"
                ports: 
                  - "8888:8888"
                volumes:
                  - type: bind
                    source: "{{ docker_chronograf.volume }}"
                    target: /var/lib/chronograf
                networks:
                    - tickstacknet
              kapacitor:
                image: "{{ docker_kapacitor.image }}"
                volumes:
                  - type: bind
                    source: "{{ docker_kapacitor.volume }}"
                    target: /var/lib/kapacitor
                environment:
                  KAPACITOR_INFLUXDB_0_URLS_0: http://influxdb:8086
                networks:
                    - tickstacknet
            networks:
                tickstacknet:
  run_once: true
