- name: Deploy Visualiser service
  docker_swarm_service:
    name: visualizer
    image: "{{ docker_vizualizer.image }}"
    publish: 
        - published_port: 8081
          target_port: 8080
    mounts:
      - source: /var/run/docker.sock
        target: /var/run/docker.sock
        type: bind
    placement:
      constraints:
        - "node.role==manager"
    restart_config:
      condition: any
  run_once: true
