- name: Install git on leader node
  apt:
    name: 
        - git
    state: present

- name: Pull visualizer repo
  git:
      repo: https://github.com/dockersamples/docker-swarm-visualizer.git
      dest: visualizer

- name: Build the image and push it to the private repo
  docker_image:
    build:
      path: visualizer
      pull: yes
    name: "{{ docker_vizualizer.image }}"
    push: yes
    source: build
    force_source: yes

- name: Deploy Visualiser service
  docker_swarm_service:
    name: visualizer
    image: "{{ docker_vizualizer.image }}"
    publish: 
        - published_port: 8081
          target_port: 8080
    mounts:
      - source: /var/run/docker.sock
        target: /var/run/docker.sock
        type: bind
    placement:
      constraints:
        - "node.role==manager"
    restart_config:
      condition: any
  run_once: true
