- name: Pull visualizer image to all nodes
  docker_image:
    name: njdcourtney/visualizer-custom:latest

- name: Deploy Visualiser service
  when: "'ClusterManagers' in group_names"
  docker_swarm_service:
    name: visualizer
    image: njdcourtney/visualizer-custom:latest
    publish: 
        - published_port: 8080
          target_port: 8080
    constraints: 
        - "node.role==manager"
    mounts:
      - source: /var/run/docker.sock
        target: /var/run/docker.sock
        type: bind
    update_monitor: 10000
    restart_policy: any
  run_once: true
