- name: Add Resilio Sync Public Key
  apt_key:
    url: https://linux-packages.resilio.com/resilio-sync/key.asc
    state: present

- name: Add Resilio Sync Repo
  apt_repository:
    repo: deb [arch=armhf] http://linux-packages.resilio.com/resilio-sync/deb resilio-sync non-free
    state: present
    update_cache: yes

- name: Install resilio-sync
  apt:
    name: resilio-sync
    state: present

- name: Make systemd override directory
  file:
    path: /etc/systemd/system/resilio-sync.service.d
    state: directory

- name: Make systemd override config file
  copy:
    dest: /etc/systemd/system/resilio-sync.service.d/override.conf
    content: |
        [Service]
        User={{ resilio_sync_user }}
        Group={{ resilio_sync_user }}
        PIDFile=/home/{{ resilio_sync_user }}/.config/resilio-sync/sync.pid
        ExecStart=
        ExecStart=/usr/bin/rslsync --config /home/{{ resilio_sync_user }}/.config/resilio-sync/config.json
  notify: restart-resilio-sync

- name: Make systemd override directory
  file:
    path: /home/{{ resilio_sync_user }}/.config/resilio-sync/storage
    state: directory
    owner: "{{ resilio_sync_user }}"

- name: Add user config dir
  copy:
    dest: /home/{{ resilio_sync_user }}/.config/resilio-sync/config.json
    content: |
        {
        "storage_path" : "/home/{{ resilio_sync_user }}/.config/resilio-sync/storage",
        "pid_file" : "/home/{{ resilio_sync_user }}/.config/resilio-sync/sync.pid",
        "webui" :
            {
                "force_https" : true,
                "listen" : "0.0.0.0:8888"
            }
        }
  notify: restart-resilio-sync

- name: Open firewall port to GUI
  become: yes
  ufw:
    rule: allow
    port: 8888
    from_ip: '192.168.0.0/16'
    comment: "Resilio-sync"

