- name: Mount Volume directories
  mount: 
    fstype: xfs
    src: "{{ partition }}"
    path: "/data/gluster/{{volume.key}}/brick{{index}}"
    state: mounted
    opts: "rw,inode64,noatime,nouuid"
  loop: "{{ volume.value | flatten(levels=1) }}"
  loop_control:
    loop_var: partition
    index_var: index

# Compute the brick names
- name: Process list of bricks into comma seperated string.
  set_fact:
    bricks: "{{ range(0, ( volume.value | length ) ) | map('regex_replace', '(.*)', '/data/gluster/{{volume.key}}/brick\\1/brick') | join(',') }}"

# Create the cluster volume
- name: Create Gluster Volume
  gluster_volume:
    state: present
    name: "{{ volume.key }}"
    bricks: "{{ bricks }}"
    cluster: "{{ groups.cluster }}"
    replicas: 2
  run_once: true

# Mount the created volumen
- name: Mount Volume directories
  mount: 
    fstype: glusterfs
    src: "{{ inventory_hostname }}:/{{ volume.key }}"
    path: "/mnt/gluster/{{volume.key}}"
    state: mounted
