- name: Install needed packages
  apt:
    name: 
      - glusterfs-server
    state: present

- name: Allow unrestricted communication between cluster peers
  ufw:
    rule: allow
    from_ip: "{{ hostvars[item].ansible_default_ipv4.address }}"
    comment: "Cluster peer"
  with_items: " {{ groups.cluster }}"

- name: Initialise Gluster pool on one node
  gluster_peer:
    state: present
    nodes: "{{ groups.cluster }}"
  run_once: true

- name: Ensure all node are joined to the trusted pool
  gluster_peer:
    state: present
    nodes: "{{ groups.cluster }}"

- name: Mount partitions
  include_tasks: create_volumes.yml
  loop: "{{ gluster_volumes | dict2items }}"
  loop_control:
    loop_var: volume