- name: Install needed packages
  apt:
    name: 
      - xfsprogs
      - glusterfs-server
    state: present

- name: Create a Gluster trusted storage pool
  gluster_peer:
    state: present
    nodes: "{{ groups.cluster }}"

- name: Mount partitions and create gluster volumes
  include_tasks: create_volumes.yml
  loop: "{{ gluster_volumes | dict2items }}"
  loop_control:
    loop_var: volume
