- name: Get Gluster physical device partition table
  parted: 
    device: "{{ device }}"
    unit: MiB
  register: device_info

- name: Delete every partition.
  parted:
    device: "{{ device }}"
    number: "{{ item.num }}"
    state: absent
  with_items: "{{ device_info.partitions }}"

- name: Make partitions (1 of 2)
  parted:
    device: "{{ device }}"
    number: 1
    state: present
    part_start: 0%
    part_end: 50%

- name: Create the xfs filesystem on the Gluster device (1 of 2)
  filesystem:
    fstype: xfs
    dev: "{{ device }}1"
    force: true

- name: Make partitions (2 of 2)
  parted:
    device: "{{ device }}"
    number: 2
    state: present
    part_start: 50%
    part_end: 100%

- name: Create the xfs filesystem on the Gluster device (2 of 2)
  filesystem:
    fstype: xfs
    dev: "{{ device }}2"
    force: true
