- name: Pull the tickstack images to all nodes
  docker_image:
    source: pull
    name: "{{ item }}"
  loop:
    - "{{ tickstack.services.influxdb.image }}"
    - "{{ tickstack.services.chronograf.image }}"

- name: Ensure the mount directories exist
  become: yes
  file:
    name: "{{ item }}"
    state: directory
  loop:
    - "{{ tickstack.services.influxdb.volumes[0].source }}"
    - "{{ tickstack.services.chronograf.volumes[0].source }}"

- name: Deploy the monitoring service stack
  when: "'ClusterManagers' in group_names" 
  docker_stack:
        state: present
        name: tickstack
        compose:
          - "{{ tickstack }}"
  run_once: true