- name: Update Hosts file contents with static servers
  blockinfile:
    path: /etc/hosts
    block: "{{ dnsmasq_vars.static_hosts | join('\n') }}"
  notify: restart-dnsmasq

- name: Install dnsmasq
  apt:
    name: dnsmasq
    state: present

- name: Configure dnsmasq
  template:
    src: dnsmasq.conf.j2
    dest: /etc/dnsmasq.conf
    owner: root
    group: root
    mode: "u=rw,g=r,o=r"
  notify: restart-dnsmasq

- name: Open firewall ports
  ufw:
    rule: allow
    port: "{{ item }}"
    comment: DNSMasq DNS and DHCP
  loop:
      - 53
      - 67