- name: Install prerequisites
  apt:
    name: 
        - apt-transport-https
        - ca-certificates
        - python-pip
    state: present

- name: Install Docker python module (Ansible module pre-req)
  pip:
    name: docker

- name: Add Docker Public Key
  apt_key:
    url: https://download.docker.com/linux/raspbian/gpg
    state: present

- name: Add Docker Repo
  apt_repository:
    repo: deb [arch=armhf] https://download.docker.com/linux/raspbian stretch stable
    state: present
    update_cache: yes

- name: Install docker-ce
  apt:
    name: docker-ce
    install_recommends: no
    state: present

- name: Start the swarm with default parameters
  when: "'cluster-manager' in group_names" 
  docker_swarm:
    state: present
  register: swarm_info
  run_once: true

- name: Add worker nodes to the swarm
  docker_swarm:
    state: join
    advertise_addr: "{{ ansible_default_ipv4.address }}"
    join_token: "{{ hostvars[groups['cluster-manager'][0]].swarm_info.swarm_facts.JoinTokens.Worker }}"
    remote_addrs: [ "{{ hostvars[groups['cluster-manager'][0]].ansible_default_ipv4.address }}:2377" ]
