# Raspberry Pi has a default username and password, add a new admin user so
# the default user can be deleted later.
# This playbook is designed to be used just once when a pi is first installed.
# This is the one and only time that we'll use the default 'pi' user

- name: Add new admin user to newly installed Pi
  hosts: pi
  become: yes
  gather_facts: false
  vars:
    # This is the well-known default username and password that 
    # we're actively changing.
    ansible_ssh_user: pi 
    ansible_ssh_pass: raspberry

  tasks:
    - name: Create admin user
      user:
        name: "{{ admin_user }}"
        generate_ssh_key: yes
        password: "{{ admin_password }}"
        shell: /bin/bash

    - name: Add management station ssh key to admin user authorized keys
      authorized_key:
        user: "{{ admin_user }}"
        state: present
        key: "{{ admin_ssh_key }}"

    - name: Add extra groups to admin user
      user:
        name: "{{ admin_user }}"
        groups: "{{ admin_groups }}"
        append: yes

    - name: Add sudoers entry to allow admin user passwordless sudo
      copy:
        content: "{{ admin_user }} ALL=(ALL) NOPASSWD: ALL"
        dest: "/etc/sudoers.d/020_{{ admin_user }}-nopasswd"
        mode: 0440
    
    # A newly install pi almost certainly needs a software update
    #  Run async as the first software update can take some time.
    - name: Update software
      apt:
        update_cache: yes
        cache_valid_time: 3600
        upgrade: yes
      async: 300
      poll: 10
    
    # Reboot the server after the update
    - name: Rebooting
      shell: sleep 2 && shutdown -r now 'Reboot required'
      async: 1
      poll: 0
