# Invocation
# ansible-playbook 02-gluster.yml -i hosts
#
# Installation and configuration of a Gluster peer group and volume

- name: Configure GlusterFS
  hosts: cluster
  remote_user: "{{ admin_user }}"
  become: yes
  gather_facts: true

  tasks:
    - name: Install needed packages
      apt:
        name: 
          - xfsprogs
          - glusterfs-server
        state: present

    - name: Get Gluster physical device partition table
      parted: 
        device: "{{ gluster_device }}"
        unit: MiB
      register: device_info

    - name: Delete every partition except the first one.
      parted:
        device: "{{ gluster_device }}"
        number: "{{ item.num }}"
        state: absent
      with_items: "{{ device_info.partitions[1:] }}"

    - name: Expand first partition to take up the full disk
      parted:
        device: "{{ gluster_device }}"
        number: 1
        state: present
        part_start: 0%
        part_end: 100%

    - name: Create the xfs filesystem on the Gluster device
      filesystem:
        fstype: xfs
        dev: "{{ gluster_device }}1"

    - name: Add brick to fstab
      mount: 
        fstype: xfs
        src: "{{ gluster_device }}1"
        path: "/data/gluster/{{gluster_volume}}"
        state: mounted
        opts: "rw,inode64,noatime,nouuid"

    - name: Allow unrestricted communication between cluster peers
      ufw:
        rule: allow
        from_ip: "{{ hostvars[item].ansible_default_ipv4.address }}"
        comment: "Gluster peer"
      with_items: " {{ groups.cluster }}"

    - name: Create a Gluster trusted storage pool
      gluster_peer:
        state: present
        nodes: "{{ groups.cluster }}"
    
    - name: create gluster volume
      gluster_volume:
        state: present
        name: "{{ gluster_volume }}"
        bricks: /data/gluster/Shared/brick1
        rebalance: yes
        cluster: "{{ groups.cluster }}"
      run_once: true