# Invocation
# ansible-playbook 02-gluster.yml -i hosts
#
# Installation and configuration of a Gluster peer group and volume

- name: Configure GlusterFS
  hosts: cluster
  remote_user: "{{ admin_user }}"
  become: yes
  gather_facts: true

  tasks:
    - import_role:
        name: gluster
