# Installation and configuration of a Gluster peer group and volume

- name: Install GlusterFS and docker
  hosts: cluster
  remote_user: "{{ admin_user }}"
  become: yes
  gather_facts: true

  tasks:
    - name: Install GlusterFS
      import_role:
        name: gluster

    # - name: Install Docker Swarm
    #   import_role:
    #     name: docker

