- name: Create the Hive database
  influxdb_database:
      hostname: "{{ vault_influxdb.hostname }}"
      database_name: "hive"
      login_username: "{{ vault_influxdb.username }}"
      login_password: "{{ vault_influxdb.password }}"
      
- name: create 90d retention policy
  influxdb_retention_policy:
      hostname: "{{ vault_influxdb.hostname }}"
      database_name: "hive"
      login_username: "{{ vault_influxdb.username }}"
      login_password: "{{ vault_influxdb.password }}"
      policy_name: "autogen"
      duration: '90d'
      replication: 1
      default: yes

- name: Create Hive volume Directories
  file:
    name: "{{ docker_volumes_dir }}/hive"
    state: directory

- name: Generate config file
  template:
    src: Hive/config.yml.j2
    dest: "{{ docker_volumes_dir }}/hive/config.yml"

- name: Install git on leader node
  apt:
    name: 
      - git
    state: present

- name: Pull hive repo
  git:
      repo: https://github.com/njdcourtney/Hive.git
      dest: hive
  register: docker_hive_source

- name: Rebuild image if required
  import_tasks: build_image.yml
  when: docker_hive_source.changed
  vars:
    docker_build:
      image: "njdcourtney/pi-hive"
      path: "hive"

- name: Deploy Hive service
  docker_swarm_service:
    name: hive
    image: njdcourtney/pi-hive
    resolve_image: true
    mounts:
      - type: bind
        source: "{{ docker_volumes_dir }}/hive/config.yml"
        target: /app/config.yml
    restart_config:
      condition: on-failure
  tags: hive-service
