- name: Get facts
  setup:
    gather_subset:
      - '!all'
      - network
  register: network_facts
  run_once: true
  delegate_to: "{{ docker_cluster_leader }}"

- name: Install Docker prerequisites
  apt:
    name: 
        - apt-transport-https
        - ca-certificates
        - python3-pip
    state: present

- name: Install Docker python modules (Ansible docker modules pre-reqs)
  pip:
    name: 
        - docker
        - jsondiff
        - pyyaml

- name: Add Docker Public Key
  apt_key:
    url: https://download.docker.com/linux/raspbian/gpg
    state: present

- name: Add Docker Repo
  apt_repository:
    repo: deb [arch=armhf] https://download.docker.com/linux/raspbian buster stable
    state: present
    update_cache: yes

- name: Install docker-ce
  apt:
    name: docker-ce
    install_recommends: no
    state: present

- name: Add admin user to docker group
  user:
    name: "{{ admin_user }}"
    groups: docker
    append: yes

- name: Update the systemd file if using gluster
  when: docker_run_after_gluster is defined and docker_run_after_gluster
  lineinfile:
    path: /etc/systemd/system/multi-user.target.wants/docker.service
    regexp: '^After='
    line: 'After=network-online.target firewalld.service containerd.service glusterd.service'
  
- name: Start the swarm with default parameters
  docker_swarm:
    state: present
  register: swarm_info
  run_once: true
  delegate_to: "{{ docker_cluster_leader }}"

- name: Add nodes to the swarm
  docker_swarm:
    state: join
    advertise_addr: "eth0"
    join_token: "{{ swarm_info.swarm_facts.JoinTokens.Manager }}"
    remote_addrs: [ "{{ network_facts.ansible_facts.ansible_default_ipv4.address }}:2377" ]

- name: Deploy Cluster Services
  block:
    - include_tasks: vizualizer.yml
    - include_tasks: tickstack.yml
  tags: docker-services
  run_once: true
  delegate_to: "{{ docker_cluster_leader }}"

- name: Docker Cleanup
  docker_prune:
    containers: yes
    images: yes