- name: Get facts
  gather_facts:

- name: Install prerequisites
  apt:
    name: 
        - apt-transport-https
        - ca-certificates
        - python-pip
    state: present

- name: Install Docker python modules (Ansible docker modules pre-reqs)
  pip:
    name: 
        - docker
        - jsondiff
        - pyyaml

- name: Add Docker Public Key
  apt_key:
    url: https://download.docker.com/linux/raspbian/gpg
    state: present

- name: Add Docker Repo
  apt_repository:
    repo: deb [arch=armhf] https://download.docker.com/linux/raspbian stretch stable
    state: present
    update_cache: yes

- name: Install docker-ce
  apt:
    name: docker-ce
    install_recommends: no
    state: present

- name: Add admin user to docker group
  user:
    name: "{{ admin_user }}"
    groups: docker
    append: yes

- name: Update the systemd file if using gluster
  when: docker_run_after_gluster is defined and docker_run_after_gluster
  lineinfile:
    path: /etc/systemd/system/multi-user.target.wants/docker.service
    regexp: '^After='
    line: 'After=network-online.target firewalld.service glusterfs-server.service'

- name: Create cert directory
  file:
    name: /etc/docker/certs.d/cluster:5000
    state: directory

- name: Create cert file
  copy:
    content: "{{ docker_registry_cert_crt }}"
    dest: /etc/docker/certs.d/cluster:5000/domain.crt

- import_tasks: swarm-init.yml
- import_tasks: networks.yml