- name: Create Hive volume Directories
  file:
    name: "{{ docker_volumes_dir }}/hive"
    state: directory

- name: Pull hive repo
  git:
    repo: https://github.com/njdcourtney/Hive.git
    dest: hive
  register: docker_hive_source
  
- name: Rebuild image if required
  import_tasks: build-image.yml
  when: docker_hive_source.changed
  vars:
    docker_image_name: njdcourtney/pi-hive
    docker_image_path: hive

- name: Create the Hive database
  influxdb_database:
      hostname: "{{ inventory_hostname }}"
      database_name: "hive"
      udp_port: 4444 # Bug in the module - have to specify this even when it's not used.
      login_username: "{{ vault_influxdb.username }}"
      login_password: "{{ vault_influxdb.password }}"
      
- name: create 90d retention policy
  influxdb_retention_policy:
      hostname: "{{ inventory_hostname }}"
      database_name: "hive"
      udp_port: 4444 # Bug in the module - have to specify this even when it's not used.
      login_username: "{{ vault_influxdb.username }}"
      login_password: "{{ vault_influxdb.password }}"
      policy_name: "autogen"
      duration: '90d'
      replication: 1
      default: yes
  
- name: Generate config file
  template:
    src: hive.conf.j2
    dest: "{{ docker_volumes_dir }}/hive/config.yml"

- name: Deploy Hive service
  docker_swarm_service:
    name: hive
    image: njdcourtney/pi-hive
    resolve_image: true
    force_update: "{{ docker_force_update }}"
    mounts:
      - type: bind
        source: "{{ docker_volumes_dir }}/hive/config.yml"
        target: /app/config.yml
    restart_config:
      condition: on-failure
    networks:
      - monitoring