- name: Start the swarm with default parameters
  when: "'ClusterLeader' in group_names"
  docker_swarm:
    state: present
  register: swarm_info
  run_once: true

- name: Add nodes to the swarm
  docker_swarm:
    state: join
    advertise_addr: "eth0"
    join_token: "{{ swarm_info.swarm_facts.JoinTokens.Worker }}"
    remote_addrs: [ "{{ hostvars[groups['ClusterLeader'][0]].ansible_facts.default_ipv4.address }}:2377" ]


