- name: Create Tickstack volume Directories
  file:
    name: "{{ docker_volumes_dir }}/{{ service }}"
    state: directory
  loop:
    - influxdb
    - chronograf
    - kapacitor
  loop_control:
    loop_var: service

- name: Deploy the monitoring service stack
  docker_stack:
    state: present
    name: tickstack
    prune: yes
    compose:
      - version: "3.7"
        services:
          influxdb:
            image: influxdb
            ports: 
              - "8086:8086"
            volumes:
              - type: bind
                source: "{{ docker_volumes_dir }}/influxdb"
                target: /var/lib/influxdb
            environment:
              INFLUXDB_REPORTING_DISABLED: 'true'
              INFLUXDB_HTTP_AUTH_ENABLED: 'true'
              INFLUXDB_ADMIN_USER: "{{ vault_influxdb.username }}"
              INFLUXDB_ADMIN_PASSWORD: "{{ vault_influxdb.password }}"
            networks:
              - tickstacknet
          chronograf:
            image: chronograf
            ports: 
              - "8888:8888"
            volumes:
              - type: bind
                source: "{{ docker_volumes_dir }}/chronograf"
                target: /var/lib/chronograf
            environment:
              INFLUXDB_URL: "{{ vault_influxdb.url }}"
              INFLUXDB_USERNAME: "{{ vault_influxdb.username }}"
              INFLUXDB_PASSWORD: "{{ vault_influxdb.password }}"
              KAPACITOR_URL: "http://kapacitor:9092"
              REPORTING_DISABLE: "true"
            depends_on: 
              - influxdb
            networks:
              - tickstacknet
          kapacitor:
            image: kapacitor
            volumes:
              - type: bind
                source: "{{ docker_volumes_dir }}/kapacitor"
                target: /var/lib/kapacitor
            environment:
              KAPACITOR_INFLUXDB_0_URLS_0: "{{ vault_influxdb.url }}"
              KAPACITOR_INFLUXDB_0_USERNAME: "{{ vault_influxdb.username }}"
              KAPACITOR_INFLUXDB_0_PASSWORD: "{{ vault_influxdb.password }}"
            depends_on: 
              - influxdb
            networks:
                - tickstacknet
        networks:
            tickstacknet:

- name: Wait for InfluxDB to start
  wait_for:
    port: 8086
    host: "{{ vault_influxdb.hostname }}"
    state: present
    
- name: Create the Telegraf database (may not be needed if Telegraf agent gets there first)
  influxdb_database:
      hostname: "{{ vault_influxdb.hostname }}"
      database_name: "telegraf"
      login_username: "{{ vault_influxdb.username }}"
      login_password: "{{ vault_influxdb.password }}"
      
- name: create 90d retention policy
  influxdb_retention_policy:
      hostname: "{{ vault_influxdb.hostname }}"
      database_name: "telegraf"
      login_username: "{{ vault_influxdb.username }}"
      login_password: "{{ vault_influxdb.password }}"
      policy_name: "autogen"
      duration: '90d'
      replication: 1
      default: yes
