- name: Create Tickstack volume Directories
  file:
    name: "{{ docker_volumes_dir }}/{{ service }}"
    state: directory
  loop:
    - influxdb
    - chronograf
    - kapacitor
  loop_control:
    loop_var: service

- name: Deploy the monitoring service stack
  docker_stack:
    state: present
    name: tickstack
    prune: yes
    compose:
      - version: "3.7"
        services:
          influxdb:
            image: influxdb
            ports: 
              - "8086:8086"
            volumes:
              - type: bind
                source: "{{ docker_volumes_dir }}/influxdb"
                target: /var/lib/influxdb
            environment:
              INFLUXDB_REPORTING_DISABLED: 'true'
            networks:
              - tickstacknet
          chronograf:
            image: chronograf
            ports: 
              - "8888:8888"
            volumes:
              - type: bind
                source: "{{ docker_volumes_dir }}/chronograf"
                target: /var/lib/chronograf
            networks:
              - tickstacknet
            environment:
              INFLUXDB_URL: "{{ influxdb_url }}"
              KAPACITOR_URL: "http://kapacitor:9092"
              REPORTING_DISABLE: "true"          
          kapacitor:
            image: kapacitor
            volumes:
              - type: bind
                source: "{{ docker_volumes_dir }}/kapacitor"
                target: /var/lib/kapacitor
            environment:
              KAPACITOR_INFLUXDB_0_URLS_0: "{{ influxdb_url }}"
            networks:
                - tickstacknet
        networks:
            tickstacknet:
