- name: Create Tiddywiki volume directory
  file:
    name: "{{ docker_volumes_dir }}/tiddywiki"
    state: directory

- name: Copy build files to build node
  copy: 
    src: Tiddywiki/
    dest: Tiddywiki
    mode: preserve
  register: docker_tiddywiki_source

- name: Rebuild image if required
  import_tasks: build_image.yml
  when: docker_tiddywiki_source.changed
  vars:
    docker_build:
      image: "njdcourtney/pi-tiddywiki"
      path: "Tiddywiki"
  
- name: Stop service if doing a forced update
  when: tiddywikis.credentials.force_update is defined and tiddywikis.credentials.force_update
  docker_swarm_service:
    name: "tiddywiki_{{ item.name }}"
    state: absent
  loop: "{{ tiddywikis.wikis }}"

- name: Delete the secret if doing a forced update
  when: tiddywikis.credentials.force_update is defined and tiddywikis.credentials.force_update
  docker_secret:
    name: tiddywiki-credentials
    state: absent

- name: Create the tiddywiki-credentials secret
  docker_secret:
    name: tiddywiki-credentials
    data: "{{ tiddywikis.credentials.secret }}"
    state: present

- name: Deploy Tiddywiki service
  docker_swarm_service:
    name: "tiddywiki_{{ item.name }}"
    image: njdcourtney/pi-tiddywiki
    resolve_image: true
    publish: 
        - published_port: "{{ item.port }}"
          target_port: 8090
    mounts:
      - type: bind
        source: "{{ docker_volumes_dir }}/tiddywiki"
        target: /var/lib/tiddlywiki
    env:
      WIKI_NAME: "{{ item.name }}"
    secrets:
      - secret_name: tiddywiki-credentials
    restart_config:
      condition: on-failure
  loop: "{{ tiddywikis.wikis }}"

