- name: Install git on leader node
  apt:
    name: 
        - git
    state: present

- name: Pull visualizer repo
  git:
      repo: https://github.com/dockersamples/docker-swarm-visualizer.git
      dest: visualizer
  register: docker_visualizer_source

- name: Rebuild image if required
  import_tasks: build_image.yml
  when: docker_visualizer_source.changed
  vars:
    docker_build:
      image: njdcourtney/pi-vizualizer
      path: "visualizer"

- name: Deploy Visualizer service
  docker_swarm_service:
    name: visualizer
    image: njdcourtney/pi-vizualizer
    resolve_image: true
    force_update: "{{ docker_force_update }}"
    publish: 
        - published_port: 8080
          target_port: 8080
    mounts:
      - source: /var/run/docker.sock
        target: /var/run/docker.sock
        readonly: yes
        type: bind
    placement:
      constraints:
        - "node.role==manager"
    restart_config:
      condition: on-failure
