- name: Add Ubiquiti Public Key
  apt_key:
    url: https://dl.ubnt.com/unifi/unifi-repo.gpg 
    state: present

- name: Add Ubiquiti Repo
  apt_repository:
    repo: deb http://www.ubnt.com/downloads/unifi/debian stable ubiquiti
    state: present
    update_cache: yes

- name: Add Ubuntu public key
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: 36A1D7869245C8950F966E92D8576A8BA88D21E9

- name: Add Oracle Java Repo
  apt_repository:
    repo: "ppa:webupd8team/java"
    codename: xenial
    state: present
    update_cache: yes

- name: Accept Oracle license agreement
  debconf:
    name: "oracle-java8-installer"
    question: "shared/accepted-oracle-license-v1-1"
    value: "true"
    vtype: "select"

- name: Install java and UniFi controller (can be slow)
  apt:
    name: 
      - oracle-java8-installer
      - unifi
    state: present
  notify: "server reboot"

- name: Disable the default mongodb service
  systemd:
    name: mongodb
    state: stopped
    enabled: no

# Firewall ports from https://help.ubnt.com/hc/en-us/articles/218506997-UniFi-Ports-Used
- name: Open firewall ports
  ufw:
    rule: allow
    port: "{{ item }}"
    comment: "Unifi controller"
    from_ip: '192.168.0.0/16'
  with_items:
    - 1900
    - 3478
    - 6789
    - 8080
    - 8443
    - 8880
    - 8843
    - 10001
