- name: Add Ubiquiti Public Key
  apt_key:
    url: https://dl.ubnt.com/unifi/unifi-repo.gpg 
    state: present

- name: Add Ubiquiti Repo
  apt_repository:
    repo: deb http://www.ubnt.com/downloads/unifi/debian stable ubiquiti
    state: present
    update_cache: yes

- name: Install java and UniFi controller (can be slow)
  apt:
    name: 
      - openjdk-8-jre-headless
      - unifi
    state: present
  notify: "server reboot"

- name: Disable the default mongodb service
  systemd:
    name: mongodb
    state: stopped
    enabled: no

# Firewall ports from https://help.ubnt.com/hc/en-us/articles/218506997-UniFi-Ports-Used
- name: Open firewall ports
  ufw:
    rule: allow
    port: "{{ item }}"
    comment: "Unifi controller"
    from_ip: '192.168.0.0/16'
  with_items:
    - '1900'
    - '3478'
    - '6789'
    - '8080'
    - '8443'
    - '8880'
    - '8843'
    - '10001'
